### ISSUE TITLE
Use NONE instead of none

### ISSUE THREAD

**Issue by flyingsl0ths** [M3nny/catppuccin-vim#1]
When sourcing the script usage of "none" triggers errors, specifically on lines:
https://github.com/M3nny/catppuccin-vim/blob/main/colors/catppuccin.vim#L14
https://github.com/M3nny/catppuccin-vim/blob/main/colors/catppuccin.vim#L15
https://github.com/M3nny/catppuccin-vim/blob/main/colors/catppuccin.vim#L17

**Comment by M3nny** [comment]
Thanks for your contribution, unfortunately I did not see the error as NeoVim does not throw this error
